services:
  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - brewflow-network
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: mLWQJGmWRmWe2Qdy3KJm2A
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 3
    healthcheck:
      test: ["CMD-SHELL", "timeout 10 bash -c 'cat < /dev/null > /dev/tcp/localhost/9092' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - brewflow-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:9411/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  user-service:
    image: brewflow/user-service:latest
    container_name: user-service
    networks:
      - brewflow-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    expose:
      - "8081"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8081/actuator/health | grep UP || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      zipkin:
        condition: service_healthy

  order-service:
    image: brewflow/order-service:latest
    container_name: order-service
    networks:
      - brewflow-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      USER_SERVICE_BASE_URL: http://user-service:8081
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    expose:
      - "8082"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8082/actuator/health | grep UP || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      kafka:
        condition: service_healthy
      user-service:
        condition: service_healthy
      zipkin:
        condition: service_healthy

  payment-service:
    image: brewflow/payment-service:latest
    container_name: payment-service
    networks:
      - brewflow-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    expose:
      - "8083"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8083/actuator/health | grep UP || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      kafka:
        condition: service_healthy
      zipkin:
        condition: service_healthy

  notification-service:
    image: brewflow/notification-service:latest
    container_name: notification-service
    networks:
      - brewflow-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      BREWFLOW_MAIL_USERNAME: ${BREWFLOW_MAIL_USERNAME}
      BREWFLOW_MAIL_PASSWORD: ${BREWFLOW_MAIL_PASSWORD}
    expose:
      - "8084"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8084/actuator/health | grep UP || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      kafka:
        condition: service_healthy
      zipkin:
        condition: service_healthy

  api-gateway:
    image: brewflow/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - brewflow-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      user-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      zipkin:
        condition: service_healthy

volumes:
  kafka-data:
    driver: local

networks:
  brewflow-network:
    driver: bridge