server:
  port: 8083

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: localhost:9092
    client-id: ${spring.application.name}
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.lifevaluable.brewflow.*"
        spring.json.type.mapping: orderCreated:ru.lifevaluable.brewflow.payment.event.OrderCreatedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        allow.auto.create.topics: true
        spring.json.type.mapping: paymentProcessed:ru.lifevaluable.brewflow.payment.event.PaymentProcessedEvent

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    ru.lifevaluable.brewflow: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%15.15t] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
