{
 "title": "Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(application)" } },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$app_name\", uri!~\"/actuator/.*\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!~\"/actuator/.*\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{application=\"$app_name\", uri!~\"/actuator/.*\"}) / sum by(uri)(http_server_requests_seconds_count{application=\"$app_name\", uri!~\"/actuator/.*\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$app_name\", outcome=\"SERVER_ERROR\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", status=~\"2.*\", uri!~\"/actuator/.*\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!~\"/actuator/.*\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", status=~\"5.*\", uri!~\"/actuator/.*\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!~\"/actuator/.*\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_requests_seconds_bucket{application=\"$app_name\", uri!~\"/actuator/.*\"}[1m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{application=\"$app_name\", uri!~\"/actuator/.*\"}[1m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$app_name\", uri!~\"/actuator/.*\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{application=\"$app_name\", uri!~\"/actuator/.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(type) (\n  rate({app=~\"(.*-service|api-gateway)\"} \n    | pattern `<time> [<_>] <type> [<_>] <_> - <msg>` \n    | type != \"\" \n    |= \"$log_keyword\" \n    [1m]\n  )\n)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log of All Spring Boot Apps",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\"(.*-service|api-gateway)\"} \n| json \n| line_format \"{{.log}}\" \n| pattern `<time> [<_>] <type> [<trace_id>,<_>] <_> - <msg>` \n| line_format \"{{.app}}\\t{{.type}}\\ttrace_id={{.trace_id}}\\t{{.msg}}\" \n|= \"$log_keyword\"\n"
    }
   ]
  }
 ]
}